import { Form, FormGroup, Label, Input, Card, CardBody, Table } from "reactstrap";
import { JobListingButton } from "./JobListingButton";
import { useState } from "react";
import "./JobListing.css";
import jsonJobs from "./JobCategories.json";
import { JobList } from "./JobList";

// Makes A Job Listing Button given title, career, and salary

export function makeJobProps(title: string, career: string, salary: string) {
    return [title, career, salary];
}

export function JobListing() {
    const [jobCategoryNameList, setjobCategoryNameList] = useState([]); // State variable for array of job category names

    const [inputText, setInputText] = useState("");
    let inputHandler = (e: any) => {
        var lowerCase = e.target.value.toLowerCase();
        setInputText(lowerCase);
    }

    let categoryChangeHandler = (jobCategoryName: any) => {
        // Handles a new list of recommended job categories being generated by GPT
        setjobCategoryNameList(jobCategoryName);
    }

    return (
        <>
            <Card style={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
            <CardBody>
                <Form>
                <FormGroup>
                    <Label for="test-category-state">Enter a list of job categories...</Label>
                    <br />
                    <Input id="test-category-state" type="text" onChange={categoryChangeHandler}></Input>
                </FormGroup>
                <FormGroup>
                    <Label for="job-listing-input">Enter a job category...</Label>
                    <br />
                    <Input id="job-listing-input" type="text" onChange={inputHandler}></Input>
                </FormGroup>
                </Form>
                <p> Test </p>
                <JobList input={inputText} input2={jobCategoryNameList}></JobList>
            </CardBody>
            </Card>
        </>
    );
}